# Generated by Django 5.0.3 on 2025-12-05 04:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staffNumber', models.CharField(blank=True, max_length=255, null=True)),
                ('prefix', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('other_name', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('surname', models.CharField(blank=True, max_length=255, null=True)),
                ('file', models.ImageField(blank=True, default=False, null=True, upload_to='UslStaffImage/')),
                ('dob', models.DateField(default=None)),
                ('nationality', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('region', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('gender', models.CharField(blank=True, default=None, max_length=25, null=True)),
                ('qualifications', models.TextField(blank=True, max_length=255, null=True)),
                ('highest_qualification', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, default=None, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('data_sync', models.BooleanField(blank=True, default=False, null=True)),
                ('created_online', models.BooleanField(blank=True, default=False, null=True)),
                ('currentStatus', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('grade', models.BooleanField(blank=True, default=False, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('recordOwner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_recordOwner', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('update_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_update_by', to=settings.AUTH_USER_MODEL, verbose_name='Update by')),
            ],
        ),
    ]
