# Generated by Django 5.0.3 on 2025-12-05 04:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('credentials', '0001_initial'),
        ('institutions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_date', models.DateField(unique=True)),
                ('total_verifications', models.PositiveIntegerField(default=0)),
                ('valid_verifications', models.PositiveIntegerField(default=0)),
                ('invalid_verifications', models.PositiveIntegerField(default=0)),
                ('revoked_verifications', models.PositiveIntegerField(default=0)),
                ('not_found_verifications', models.PositiveIntegerField(default=0)),
                ('by_credential_id', models.PositiveIntegerField(default=0)),
                ('by_blockchain_hash', models.PositiveIntegerField(default=0)),
                ('by_qr_code', models.PositiveIntegerField(default=0)),
                ('by_share_link', models.PositiveIntegerField(default=0)),
                ('by_api', models.PositiveIntegerField(default=0)),
                ('avg_response_time_ms', models.FloatField(default=0)),
                ('top_verifiers', models.JSONField(blank=True, default=list)),
                ('top_credentials', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Verification Report',
                'verbose_name_plural': 'Verification Reports',
                'ordering': ['-report_date'],
            },
        ),
        migrations.CreateModel(
            name='FraudAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('multiple_failures', 'Multiple Failed Verifications'), ('unusual_pattern', 'Unusual Verification Pattern'), ('revoked_access', 'Attempting to Verify Revoked Credential'), ('fake_credential', 'Potential Fake Credential'), ('brute_force', 'Brute Force Attempt')], max_length=30)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('credential', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='credentials.credential')),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='institutions.institution')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fraud Alert',
                'verbose_name_plural': 'Fraud Alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VerificationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('credential_id_searched', models.CharField(blank=True, max_length=100)),
                ('verifier_company', models.CharField(blank=True, max_length=200)),
                ('verifier_email', models.EmailField(blank=True, max_length=254)),
                ('method', models.CharField(choices=[('credential_id', 'Credential ID'), ('blockchain_hash', 'Blockchain Hash'), ('qr_code', 'QR Code Scan'), ('share_link', 'Share Link'), ('api', 'API Request')], default='credential_id', max_length=20)),
                ('result', models.CharField(choices=[('valid', 'Valid'), ('invalid', 'Invalid'), ('revoked', 'Revoked'), ('expired', 'Expired'), ('not_found', 'Not Found'), ('error', 'Error')], max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('response_time_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('credential', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_logs', to='credentials.credential')),
                ('verifier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verifications_performed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Verification Log',
                'verbose_name_plural': 'Verification Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
