# Generated by Django 5.0.3 on 2025-12-05 04:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=300)),
                ('short_name', models.CharField(blank=True, max_length=50)),
                ('institution_type', models.CharField(choices=[('university', 'University'), ('college', 'College'), ('polytechnic', 'Polytechnic'), ('vocational', 'Vocational Institute'), ('professional', 'Professional Body'), ('government', 'Government Agency')], default='university', max_length=20)),
                ('whed_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('website', models.URLField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('country', models.CharField(db_index=True, max_length=100)),
                ('country_code', models.CharField(blank=True, max_length=3)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('address', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='institution_logos/')),
                ('accreditation_status', models.CharField(choices=[('accredited', 'Accredited'), ('pending', 'Pending Review'), ('probation', 'On Probation'), ('revoked', 'Accreditation Revoked'), ('not_accredited', 'Not Accredited')], default='pending', max_length=20)),
                ('accreditation_body', models.CharField(blank=True, max_length=200)),
                ('accreditation_date', models.DateField(blank=True, null=True)),
                ('accreditation_expiry', models.DateField(blank=True, null=True)),
                ('founded_year', models.PositiveIntegerField(blank=True, null=True)),
                ('is_partner', models.BooleanField(default=False)),
                ('partner_since', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('blockchain_address', models.CharField(blank=True, max_length=100)),
                ('public_key', models.TextField(blank=True)),
                ('total_credentials_issued', models.PositiveIntegerField(default=0)),
                ('total_students', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Institution',
                'verbose_name_plural': 'Institutions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AccreditationRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('accreditation_body', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('accredited', 'Accredited'), ('pending', 'Pending Review'), ('probation', 'On Probation'), ('revoked', 'Accreditation Revoked'), ('not_accredited', 'Not Accredited')], max_length=20)),
                ('granted_date', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('certificate_number', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('certificate_document', models.FileField(blank=True, null=True, upload_to='accreditation_certificates/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accreditation_history', to='institutions.institution')),
            ],
            options={
                'verbose_name': 'Accreditation Record',
                'verbose_name_plural': 'Accreditation Records',
                'ordering': ['-granted_date'],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('code', models.CharField(blank=True, max_length=50)),
                ('degree_level', models.CharField(choices=[('certificate', 'Certificate'), ('diploma', 'Diploma'), ('associate', 'Associate Degree'), ('bachelor', "Bachelor's Degree"), ('master', "Master's Degree"), ('doctorate', 'Doctorate'), ('professional', 'Professional Degree')], default='bachelor', max_length=20)),
                ('department', models.CharField(blank=True, max_length=200)),
                ('faculty', models.CharField(blank=True, max_length=200)),
                ('duration_years', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='institutions.institution')),
            ],
            options={
                'verbose_name': 'Program',
                'verbose_name_plural': 'Programs',
                'ordering': ['name'],
                'unique_together': {('institution', 'code')},
            },
        ),
    ]
