# Generated by Django 5.0.3 on 2025-12-05 04:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccreditationBody',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('short_name', models.CharField(blank=True, max_length=50)),
                ('country', models.CharField(max_length=100)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('body_type', models.CharField(choices=[('national', 'National Agency'), ('regional', 'Regional Body'), ('international', 'International Organization'), ('professional', 'Professional Association')], default='national', max_length=20)),
                ('website', models.URLField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('is_recognized', models.BooleanField(default=True)),
                ('recognized_by', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Accreditation Body',
                'verbose_name_plural': 'Accreditation Bodies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WHEDRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('whed_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('institution_name', models.CharField(db_index=True, max_length=300)),
                ('institution_name_local', models.CharField(blank=True, max_length=300)),
                ('country', models.CharField(db_index=True, max_length=100)),
                ('country_code', models.CharField(max_length=3)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('address', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('institution_type', models.CharField(blank=True, max_length=100)),
                ('founded_year', models.PositiveIntegerField(blank=True, null=True)),
                ('is_accredited', models.BooleanField(default=True)),
                ('accreditation_body', models.CharField(blank=True, max_length=200)),
                ('last_updated', models.DateField(blank=True, null=True)),
                ('data_source', models.CharField(default='UNESCO WHED', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linked_institution', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whed_record', to='institutions.institution')),
            ],
            options={
                'verbose_name': 'WHED Record',
                'verbose_name_plural': 'WHED Records',
                'ordering': ['institution_name'],
            },
        ),
        migrations.CreateModel(
            name='AccreditationLookupLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('search_query', models.CharField(max_length=300)),
                ('search_type', models.CharField(max_length=50)),
                ('results_count', models.PositiveIntegerField(default=0)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('whed_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accreditation.whedrecord')),
            ],
            options={
                'verbose_name': 'Accreditation Lookup Log',
                'verbose_name_plural': 'Accreditation Lookup Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
