# Generated by Django 5.0.3 on 2025-12-05 04:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('credential_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('credential_type', models.CharField(choices=[('degree', 'Degree Certificate'), ('diploma', 'Diploma'), ('certificate', 'Certificate'), ('transcript', 'Transcript'), ('award', 'Award/Honor'), ('professional', 'Professional Certification')], default='degree', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval'), ('issued', 'Issued'), ('revoked', 'Revoked'), ('expired', 'Expired')], default='draft', max_length=20)),
                ('holder_name', models.CharField(max_length=200)),
                ('holder_student_id', models.CharField(blank=True, max_length=50)),
                ('holder_date_of_birth', models.DateField(blank=True, null=True)),
                ('program_name', models.CharField(max_length=300)),
                ('degree_level', models.CharField(blank=True, max_length=50)),
                ('major', models.CharField(blank=True, max_length=200)),
                ('minor', models.CharField(blank=True, max_length=200)),
                ('specialization', models.CharField(blank=True, max_length=200)),
                ('grade', models.CharField(blank=True, max_length=50)),
                ('honors', models.CharField(blank=True, max_length=200)),
                ('credits_earned', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('enrollment_date', models.DateField(blank=True, null=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('blockchain_hash', models.CharField(blank=True, db_index=True, max_length=100)),
                ('blockchain_tx_id', models.CharField(blank=True, max_length=100)),
                ('block_number', models.PositiveIntegerField(blank=True, null=True)),
                ('ipfs_hash', models.CharField(blank=True, max_length=100)),
                ('document', models.FileField(blank=True, null=True, upload_to='credentials/')),
                ('document_hash', models.CharField(blank=True, max_length=100)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('verification_url', models.URLField(blank=True)),
                ('issuer_signature', models.TextField(blank=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revocation_reason', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('holder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credentials', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credentials', to='institutions.institution')),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_credentials', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credentials', to='institutions.program')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_credentials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Credential',
                'verbose_name_plural': 'Credentials',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlockchainTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('issue', 'Credential Issued'), ('revoke', 'Credential Revoked'), ('update', 'Credential Updated')], max_length=20)),
                ('transaction_hash', models.CharField(max_length=100, unique=True)),
                ('block_number', models.PositiveIntegerField()),
                ('gas_used', models.PositiveIntegerField(blank=True, null=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('confirmations', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('credential', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blockchain_transactions', to='credentials.credential')),
            ],
            options={
                'verbose_name': 'Blockchain Transaction',
                'verbose_name_plural': 'Blockchain Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CredentialBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('total_count', models.PositiveIntegerField(default=0)),
                ('processed_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('source_file', models.FileField(blank=True, null=True, upload_to='batch_uploads/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credential_batches', to='institutions.institution')),
            ],
            options={
                'verbose_name': 'Credential Batch',
                'verbose_name_plural': 'Credential Batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CredentialShare',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('share_token', models.CharField(max_length=100, unique=True)),
                ('shared_with_email', models.EmailField(blank=True, max_length=254)),
                ('shared_with_company', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('max_views', models.PositiveIntegerField(blank=True, null=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('hide_grade', models.BooleanField(default=False)),
                ('hide_student_id', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('credential', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='credentials.credential')),
            ],
            options={
                'verbose_name': 'Credential Share',
                'verbose_name_plural': 'Credential Shares',
            },
        ),
    ]
