# Generated by Django 5.0.3 on 2025-12-05 04:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(blank=True, max_length=255, null=True)),
                ('site_name_abb', models.CharField(blank=True, max_length=255, null=True)),
                ('slogan', models.CharField(blank=True, max_length=255, null=True)),
                ('primary_color', models.CharField(blank=True, max_length=255, null=True)),
                ('secondary_color', models.CharField(blank=True, max_length=255, null=True)),
                ('file', models.ImageField(blank=True, null=True, upload_to='logo')),
                ('file_2', models.ImageField(blank=True, null=True, upload_to='logo_2s')),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('email2', models.EmailField(blank=True, max_length=255, null=True)),
                ('site_desc', models.TextField(blank=True, max_length=255, null=True)),
                ('site_keyword', models.TextField(blank=True, max_length=255, null=True)),
                ('google_code', models.CharField(blank=True, max_length=255, null=True)),
                ('street', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('street2', models.CharField(blank=True, max_length=255, null=True)),
                ('city2', models.CharField(blank=True, max_length=255, null=True)),
                ('country2', models.CharField(blank=True, max_length=255, null=True)),
                ('phone2', models.CharField(blank=True, max_length=255, null=True)),
                ('facebook', models.CharField(blank=True, max_length=255, null=True)),
                ('twitter', models.CharField(blank=True, max_length=255, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=255, null=True)),
                ('instagram', models.CharField(blank=True, max_length=255, null=True)),
                ('google', models.CharField(blank=True, max_length=255, null=True)),
                ('reddit', models.CharField(blank=True, max_length=255, null=True)),
                ('tumblr', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('check_for_fee_b4_view_grades', models.BooleanField(blank=True, default=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('data_sync', models.BooleanField(blank=True, default=False, null=True)),
                ('created_online', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number')),
                ('subject', models.CharField(max_length=255, verbose_name='Subject')),
                ('interest', models.CharField(blank=True, choices=[('volunteer', 'Volunteering'), ('donate', 'Making a Donation'), ('partner', 'Partnership Opportunities'), ('programs', 'Program Information'), ('other', 'Other')], max_length=50, null=True, verbose_name='Area of Interest')),
                ('message', models.TextField(verbose_name='Message')),
                ('status', models.CharField(choices=[('new', 'New'), ('read', 'Read'), ('replied', 'Replied'), ('archived', 'Archived')], default='new', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Internal Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Received At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('replied_at', models.DateTimeField(blank=True, null=True, verbose_name='Replied At')),
                ('replied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_replies', to=settings.AUTH_USER_MODEL, verbose_name='Replied By')),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('referer', models.URLField(blank=True, null=True, verbose_name='Referer')),
                ('path', models.CharField(max_length=500, verbose_name='Page Path')),
                ('full_path', models.URLField(blank=True, null=True, verbose_name='Full URL')),
                ('session_key', models.CharField(blank=True, max_length=40, null=True, verbose_name='Session Key')),
                ('device_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Device Type')),
                ('browser', models.CharField(blank=True, max_length=100, null=True, verbose_name='Browser')),
                ('os', models.CharField(blank=True, max_length=100, null=True, verbose_name='Operating System')),
                ('country', models.CharField(blank=True, max_length=100, null=True, verbose_name='Country')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='City')),
                ('visited_at', models.DateTimeField(auto_now_add=True, verbose_name='Visited At')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Visitor',
                'verbose_name_plural': 'Visitors',
                'ordering': ['-visited_at'],
                'indexes': [models.Index(fields=['-visited_at'], name='home_visito_visited_cade49_idx'), models.Index(fields=['ip_address'], name='home_visito_ip_addr_8e65de_idx'), models.Index(fields=['path'], name='home_visito_path_f9f507_idx')],
            },
        ),
    ]
