# Generated by Django 5.0.3 on 2025-12-07 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalsettings',
            name='check_for_fee_b4_view_grades',
        ),
    ]
