# Generated by Django 4.0.2 on 2024-12-25 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FailedAttempt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255, verbose_name='Email')),
                ('IP', models.GenericIPAddressField(null=True, verbose_name='IP Address')),
                ('failures', models.PositiveIntegerField(default=0, verbose_name='Failures')),
                ('timestamp', models.DateTimeField(auto_now=True, verbose_name='Last failed attempt')),
            ],
            options={
                'ordering': ['-timestamp'],
                'unique_together': {('email', 'IP')},
            },
        ),
    ]
